import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';
import dynamic from 'next/dynamic';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const NetworkOffline = dynamic(() => import('@/components/net-offline'), {
  loading: () => <p>Loading...</p>,
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir='rtl' lang='fa'>
      <body>
        <NetworkOffline />

        {children}

        <Toaster />
      </body>
    </html>
  );
}
